const GET_SHOPS_REQUEST = 'GET_SHOPS_REQUEST';
const GET_SHOPS_SUCCESS = 'GET_SHOPS_SUCCESS';
const GET_SHOPS_FAILED = 'GET_SHOPS_FAILED';

export {GET_SHOPS_REQUEST, GET_SHOPS_SUCCESS, GET_SHOPS_FAILED};